### ISSUE TITLE
    json.dump(preds_filt, open(resFile, 'w')) # Serialize to temporary json file. Sigh, COCO API...

### ISSUE THREAD

**Issue by mymuli** [aditya12agd5/convcap#15]
Using 5000/5000 predictions
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 72, in main
    **train(args)**
  File "/home/muli/im2txt-program/conv2cap/train.py", line 161, in train
    **scores = test(args, 'val', model_convcap=model_convcap, model_imgcnn=model_imgcnn)** 
  File "/home/muli/im2txt-program/conv2cap/test.py", line 103, in test
    **scores = language_eval(pred_captions, args.model_dir, split)**
  File "/home/muli/im2txt-program/conv2cap/evaluate.py", line 37, in language_eval
    **json.dump(preds_filt, open(resFile, 'w')) # Serialize to temporary json file. Sigh, COCO API...**
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/muli/.conda/envs/python2/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: tensor(352257) is not JSON serializable

**Excuse me, have you met this problem? How to solve it?**

**Comment by nassimaNoufail** [comment]
I have the same issue !!

**Comment by wangjiosw** [comment]
# preds_filt
[{'image_id': tensor(335981), 'caption': 'a group of people standing around a store'},... , {'image_id': tensor(74478), 'caption': 'a group of people standing around a table'}]
# transform tensor to int
```
  preds_filt = [p for p in preds if p['image_id'] in valids]
  len_p = len(preds_filt)
  for i in range(len_p):
    preds_filt[i]['image_id'] = int(preds_filt[i]['image_id'])
```
# new press_fit

[{'image_id': 335981, 'caption': 'a group of people standing around a store'},... , {'image_id': 74478, 'caption': 'a group of people standing around a table'}]

# done
